### ISSUE TITLE
Admin Functionality

### ISSUE THREAD

**Issue by emilylordahl** [htilly/zenmusic#28]
Hi there,

I have this setup so the admin and regular functions are in the same channel so I'm not getting access to the admin functions. Do you recommend just removing the conditional for `if (channel.name !== adminChannel)` to add these functions? Or am I missing something?

Thanks! My coworkers love that we have this setup.

**Comment by htilly** [comment]
Hi! 
Just so that I understand. You want everyone to get access to the admin functions, right?

If so, just change the config to:
"adminChannel" : "music"
Or what you want to call you official music channel..

And the standard channel to:
"standardChannel" : "what-ever-name"

Then you invite everyone to the "adminChannel", in this case #music and everyone should have full access...

BR
Tilly

**Comment by emilylordahl** [comment]
Cool, thanks! I'm not sure that worked but I just commented out those conditionals for now. Thank you!
